### ISSUE TITLE
Add "status" field to occupations table.

### ISSUE THREAD

**Issue by Fahrenhei7** [codelikenoob/onenewthing#4]
We have associations
user has_many :things, through: :occupations
thing has_many :users, through: :occupations

- [x] Add "status" field (which is an integer) to occupations table

**work in progress on tasks below**

- [x] Set "status" field to an enum with possible states as [:in_progress, :finished, :dropped, :want_to]

- [x] Add possibilities to change status manually by the user and RSpec tests for these actions

**Comment by lavandosovich** [comment]
Слушай, я хотел бы ее решить. Можно ее как то застолбить?

**Comment by Fahrenhei7** [comment]
@lavandosovich напишу в шапке, что выполняешь ты. Только по возможности, не растягивай на неделю, в идеале - завтра, послезавтра. :) 
Спасибо за желание помочь!

**Comment by Fahrenhei7** [comment]
@lavandosovich, прошу прощения, что не отписались тут, но один человек уже начал делать и почти доделал.
Большое спасибо за желание помочь!
